### ISSUE TITLE
reversed gene names for Q9ZUT9 and P51427

### ISSUE THREAD

**Issue by nataled** [pircurators/tracking#1]
In UniProtKB we have

Q9ZUT9 "40S ribosomal protein S5-1" (gene RPS5A) AT2G37270
P51427 "40S ribosomal protein S5-2" (gene RPS5B) AT3G11940

The sequences are non-identical.

The issue is that Araport has the gene names swapped relative to UniProtKB (that is, the first one, AT2G37270 is called RPS5B; the second, AT3G11940, is called RPS5A).

Based on one of the publications cited (link below), UniProt has it reversed. You can verify by searching the paper for the word chromosome, which indicates that RPS5A is on chromosome 3 (not 2 as you would surmise from the UniProtKB info), and vice versa for RPS5B.

http://dev.biologists.org/content/128/21/4289.long

see also

http://www.uniprot.org/uniprot/?query=Q9ZUT9+or+P51427+&sort=score

**Comment by laihokati** [comment]
These changes have been integrated to Swiss-Prot
