### ISSUE TITLE
FSCH_DICDI

### ISSUE THREAD

**Issue by nataled** [pircurators/tracking#10]
Q54DP3 (FSCH_DICDI gene fscH) is named "Frizzled/smoothened-like sans CRD protein G". Both the identifier and gene indicate the name should be "Frizzled/smoothened-like sans CRD protein H". There is an existing entry (Q54DR6 FSCG_DICDI gene fscG) that is also named "Frizzled/smoothened-like sans CRD protein G" but that one is consistent between the identifier and gene.

**Comment by laihokati** [comment]
Corrected and integrated.
