### ISSUE TITLE
incorrect gene name for Q94FB9

### ISSUE THREAD

**Issue by nataled** [pircurators/tracking#2]
The entry Q94FB9 is called "ABC transporter D family member 1" with the gene name ABCC1 in UniProtKB. Both the name and the gene name in Araport AT4G39850 (ABCD1) are consistent. I suspect the gene name in UniProtKB should be the same, ABCD1, while the entry Q9C8G9, called "ABC transporter C family member 1" stays with gene name ABCC1 (consistent between protein name, gene name, and Araport ).

**Comment by laihokati** [comment]
Gene name has been changed and integrated to Swiss-Prot
