### ISSUE TITLE
F155A_DANRE incorrect DE

### ISSUE THREAD

**Issue by nataled** [pircurators/tracking#24]
According to ZFIN, this entry is encoded by the fam155b gene, not fam155a. The actual fam155a is a TrEMBL entry (E7FA63). This is also confirmed by the tree obtained after alignment using ClustalW. I did a mini alignment using the following:

O75949
A2BDP1
Q8CCS2
B1AL88
A4IFM1
A2AWH2
E7FA63
G3X7U0

**Comment by laihokati** [comment]
Corrected version integrated.
