### ISSUE TITLE
gene name ambiguity for Q708S4 and Q708S3

### ISSUE THREAD

**Issue by nataled** [pircurators/tracking#3]
Both Q708S4 and Q708S3 are called "Acid-sensing ion channel 4" and are said to be encoded by asic4. However, each has a synonym with a more-specific name and gene (asic4.1 and asic4.2, respectively). This is confirmed by the paper already cited in the entry (PMID:14970195). ZFin changes the gene names to use "a" and "b" instead (asic4a and asic4b, respectively). I suggest that the names and genes be modified to reflect this.

**Comment by laihokati** [comment]
Names and genes have been modified to be more specific and these changes have been integrated to Swiss-Prot
