### ISSUE TITLE
incorrect DE for Q8TDR4

### ISSUE THREAD

**Issue by nataled** [pircurators/tracking#4]
Both Q8TDR4 (TCP1L_HUMAN; gene TCP10L) and B9ZVM9 (TCP2L_HUMAN; gene TCP10L2) are called "T-complex protein 10A homolog 2". Oddly, there is no human "T-complex protein 10A homolog 1". I suspect the first one should take that missing name.

**Comment by laihokati** [comment]
Corrected version integrated.
