### ISSUE TITLE
name swap for importin subunit alpha-3 and alpha-4 (human and mouse)

### ISSUE THREAD

**Issue by nataled** [pircurators/tracking#5]
This involves:

O00629 IMA3_HUMAN "Importin subunit alpha-3" gene:KPNA4
O00505 IMA4_HUMAN "Importin subunit alpha-4" gene:KPNA3
O35343 IMA3_MOUSE "Importin subunit alpha-3" gene:Kpna4
O35344 IMA4_MOUSE "Importin subunit alpha-4" gene:Kpna3

You'll notice that the names (and identifiers) are swapped in numbering relative to the gene names. Interestingly, there's a Caution note in each of the human entries which says...

for IMA3_HUMAN "Was termed importin alpha-3"
for IMA4_HUMAN "Was termed importin alpha-4"

Considering the policy of keeping protein names consistent with gene names, and those caution lines, it seems that the recommended names are swapped.

**Comment by laihokati** [comment]
The IDs and protein recommended names are correct in these cases. If you look in HGNC you will see them as synonyms. Also have a look at reference 2 in the human entries, you will find a partial amino-terminal end of these proteins and they match with what is annotated as importin subunit alpha-3 and importin subunit alpha-4 (which names come from this particular paper). It looks very confusing though and that is why there is a caution comment in the human entries (evidence pointing to the paper where these names come from).

**Comment by nataled** [comment]
Does this mean that HGNC has it wrong? So far as I know, they are the authority on human gene names.

**Comment by laihokati** [comment]
No I think HGNC has it correct too. Yes they are the authority on human gene names.
